name: Playwright Tests

on:
  push:
  schedule:
    - cron: '0 0 * * 0'  # Domingos a medianoche UTC
  workflow_dispatch:


jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps

    # üñ•Ô∏è DESKTOP
    - name: Run tests on Desktop
      run: |
        pytest -m "not mobile" \
               --capture=tee-sys \
               --html=results-desktop.html \
               --self-contained-html

    - name: Upload Desktop report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-desktop
        path: results-desktop.html

    # üì± MOBILE
    - name: Run tests on Mobile
      run: |
        pytest -m mobile \
               --capture=tee-sys \
               --html=results-mobile.html \
               --self-contained-html

    - name: Upload Mobile report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-mobile
        path: results-mobile.html

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-test-results
        path: test-results/